In [60]:
import pandas as pd
import datetime as dt
people = pd.read_csv('./data/people.csv')
def clean_people(df):
    # rename columns:
    df = df.rename(columns={'email address': 'email'})
    
    # remove rows which have an empty "first_name" (NA):
    #df = df[df.first_name.notna()] <- equivalent to next line:
    df = df.dropna(subset=['first_name'])
    
    # drop duplicates on ID column:
    df = df.drop_duplicates()
    
    # Normalize gender column:
    df['gender'] = df['gender'].replace({'Female': 'F', 'Male': 'M'})
    
    # Convert column "age" to number (coerce: put NaN for bad values):
    df['age'] = pd.to_numeric(df.age, errors='coerce')
    
    # Convert columns to date type:
    df['registration'] = pd.to_datetime(df.registration)
    df['last_seen'] = pd.to_datetime(df.last_seen, unit='s')
    # When missing, last seen should fallback to the registration date:
    df['last_seen'] = df.last_seen.combine_first(df.registration)
    
    # Add a "full_name" column by concatenating two other ones:
    df['full_name'] = df.first_name + " " + df.last_name
    
    # Add a "country" column by extracting it from the address, with a split:
    df['country'] = df.address.str.split(', ').str[1]
    
    # Column "money" contains values like "$50.23" or "€23,09".
    # We want to make it uniform (only dollar currency) and as number, not str.
    df['currency'] = df.money.str[0]  # extract first char ($/€) to a new "currency" column
    df['money'] = df.money.str[1:].str.replace(',', '.')  # extract remaining chars and replace , by .
    df['money'] = pd.to_numeric(df.money)  # convert to number
    # convert euros cells to dollar:
    df.loc[df.currency == '€', 'money'] = df[df.currency == '€'].money * 1.10
    del df['currency']  # remove "currency" column which is now useless
    
    # Keep only rows where email is not NA:
    df = df.dropna(subset=['email'])
    # Keep only rows where email is a good email:
    # CAUTION: in the real world you should not use dummy regexes like this to validate email addresses,
    # but instead use a dedicated tool like https://github.com/syrusakbary/validate_email.
    df = df[df.email.str.contains('.+@[0-9a-zA-Z\.\-_]+\.\w{2,}')]
    # Some users may use email alias (example: john.smith+truc@gmail.com is an alias for john.smith@gmail.com).
    # We want to drop these duplicates. To do that, we extract the 'alias' part with a regex:
    groups = df.email.str.extract('([0-9a-zA-Z\.\-_]+)(\+[0-9a-zA-Z\.\-_]+)?(@[0-9a-zA-Z\.\-_]+\.\w{2,})')
    df['email'] = groups[0] + groups[2]  # we override the email with the email without the alias part
    # Then, just use drop_duplicates, which will keep the first line by default:
    df = df.drop_duplicates(subset=['email'])
    
    return df

df_clean = clean_people(people)

In [68]:
df_clean["inactive"] = False
mask = (dt.datetime.today()-df_clean["last_seen"]> pd.Timedelta(days=365))
# df_clean[mask]["inactive"]= True
df_clean.loc[mask,"inactive"]=True

In [116]:
df_clean["true_phone"] =df_clean["phone"].str.contains('0[1-9].?(\d\d\.?){4}')
df_clean[["phone","true_phone"]].dropna().head(5)

/home/jorge/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

         phone true_phone
0   0136319724       True
5   0146943857       True
12  0875503094       True
15  0547556034       True
16  0811321968       True

In [117]:
df_clean["mobilephone"] =df_clean["phone"].str.contains('0[6,7].?(\d\d\.?){4}')

/home/jorge/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  """Entry point for launching an IPython kernel.

In [119]:
df_clean

,id,first_name,last_name,email,gender,age,money,lon,lat,phone,registration,inactive,last_seen,address,preference,full_name,country,true_phone,mobilephone
0,27625,Leandra,Pabelik,lpabelik5f@yale.edu,F,63.0,55.180,18.284100,49.632552,0136319724,2019-04-16,False,2019-06-03 12:39:57,"Palkovice, Czech Republic",entrée/plat/dessert,Leandra Pabelik,Czech Republic,True,False
1,27570,Ruthi,Ross,rross3w@sohu.com,F,57.0,20.370,19.230220,50.466575,NaN,2018-10-23,False,2019-08-30 11:41:04,"Siewierz, Poland",entrée/plat/dessert,Ruthi Ross,Poland,NaN,NaN
2,27572,Silas,Stourton,silas.stourton3y@answers.com,M,22.0,36.289,118.831081,24.984813,NaN,2018-12-30,False,2019-03-27 13:10:32,"Longbo, China",entrée/plat/dessert,Silas Stourton,China,NaN,NaN
3,27435,Roxine,Pettecrew,rpettecrew5@gravatar.com,F,64.0,108.823,121.648987,-8.844744,NaN,2019-03-12,False,2019-03-12 00:00:00,"Potulando, Indonesia",entrée/plat,Roxine Pettecrew,Indonesia,NaN,NaN
5,27497,Gordie,Bodicum,gbodicum1v@apache.org,M,60.0,47.260,13.978681,49.786243,0146943857,2017-04-29,False,2018-12-26 07:40:36,"Jince, Czech Republic",entrée/plat/dessert,Gordie Bodicum,Czech Republic,True,False
6,27539,Dulcine,Stopforth,dstopforth31@forbes.com,F,22.0,13.860,-35.587670,-6.255393,NaN,2017-12-13,False,2019-01-15 15:39:05,"Serrinha, Brazil",entrée/plat/dessert,Dulcine Stopforth,Brazil,NaN,NaN
7,27469,Denny,Hasnip,dhasnip13@so-net.ne.jp,F,47.0,83.567,-89.917591,14.113818,NaN,2017-05-01,False,2019-03-08 18:46:46,"Comapa, Guatemala",entrée/plat/dessert,Denny Hasnip,Guatemala,NaN,NaN
9,27565,Esmeralda,Hollindale,ehollindale3r@guardian.co.uk,F,29.0,60.590,-36.508738,-54.281149,NaN,2017-10-05,True,2018-04-12 15:45:51,"Grytviken, China",entrée/plat/dessert,Esmeralda Hollindale,China,NaN,NaN
10,27446,Skippie,Arlott,sarlottg@so-net.ne.jp,M,49.0,27.797,38.954230,55.877840,NaN,2017-08-13,True,2018-10-06 10:55:59,"Malaya Dubna, Russia",entrée/plat/dessert,Skippie Arlott,Russia,NaN,NaN
11,27550,Shermie,Locard,slocard3c@lycos.com,M,65.0,35.948,112.813530,-7.305958,NaN,2018-09-29,False,2019-05-03 00:23:45,"Wonorejo, Indonesia",entrée/plat/dessert,Shermie Locard,Indonesia,NaN,NaN
12,27548,Stanley,McCullen,smccullen3a@timesonline.co.uk,M,60.0,NaN,119.141473,28.074649,0875503094,2017-06-05,True,2017-06-05 00:00:00,"Longquan, China",entrée/plat/dessert,Stanley McCullen,China,True,False
13,27537,Lila,Yellowlees,lyellowlees2z@cdbaby.com,F,70.0,52.800,-51.528917,-29.258165,NaN,2017-05-26,False,2019-06-08 15:55:33,"Garibaldi, Brazil",entrée/plat/dessert,Lila Yellowlees,Brazil,NaN,NaN
14,27554,Ty,Havock,thavock3g@google.co.jp,M,55.0,36.003,112.044491,22.915094,NaN,2017-02-08,False,2019-09-29 06:27:12,"Yunfu, China",entrée/plat/dessert,Ty Havock,China,NaN,NaN
15,27619,Shelley,Skeemor,sskeemor59@princeton.edu,F,44.0,41.500,111.878471,-7.584917,0547556034,2019-01-24,False,2019-05-04 13:18:24,"Guyangan, Indonesia",entrée/plat/dessert,Shelley Skeemor,Indonesia,True,False
16,27442,Mort,Midford,mmidfordc@yale.edu,M,59.0,NaN,6.848501,5.959253,0811321968,2019-06-25,False,2019-06-25 00:00:00,"Ozubulu, Nigeria",entrée/plat,Mort Midford,Nigeria,True,False
17,27602,Eimile,Staterfield,estaterfield4s@cbsnews.com,F,67.0,38.510,-78.845814,-2.738998,NaN,2017-12-10,False,2019-06-27 23:11:25,"Azogues, Ecuador",entrée/plat/dessert,Eimile Staterfield,Ecuador,NaN,NaN
18,27513,Dominick,Hryncewicz,dhryncewicz2b@amazonaws.com,M,56.0,80.710,68.214686,38.530112,NaN,2017-08-04,False,2019-07-26 02:33:01,"Tursunzoda, Tajikistan",entrée/plat/dessert,Dominick Hryncewicz,Tajikistan,NaN,NaN
19,27507,Tate,Feldmann,tfeldmann25@networksolutions.com,M,NaN,92.169,30.156044,-23.411495,NaN,2017-06-06,True,2018-04-27 17:45:14,"Duiwelskloof, South Africa",entrée/plat/dessert,Tate Feldmann,South Africa,NaN,NaN
20,27462,Graig,Brownsea,gbrownseaw@arstechnica.com,M,54.0,80.230,110.393439,-7.213328,0262855559,2018-05-22,False,2019-09-28 13:28:10,"Sidomukti, Indonesia",entrée/plat/dessert,Graig Brownsea,Indonesia,True,False
21,27466,Baron,Spurrett,bspurrett10@psu.edu,M,36.0,57.560,16.580506,-18.360404,06etcetera,2018-07-20,False,2019-02-02 18:29:51,"Omuthiya, Namibia",entrée/plat/dessert,Baron Spurrett,Namibia,False,False
22,27501,Thibaud,Hatje,thatje1z@is.gd,M,24.0,56.970,-7.185387,53.158984,NaN,2017-08-21,False,2019-03-02 19:21:34,"Portarlington, Ireland",entrée/plat/dessert,Thibaud Hatje,Ireland,NaN,NaN
23,27498,Pattie,Egiloff,pegiloff1w@liveinternet.ru,M,44.0,NaN,16.931279,53.680826,NaN,2019-06-06,False,2019-06-06 00:00:00,"Czarne, Poland",entrée/plat/dessert,Pattie Egiloff,Poland,NaN,NaN
24,27563,Andre,Lugsdin,alugsdin3p@microsoft.com,M,30.0,40.630,12.219712,57.121813,0144026028,2017-01-15,False,2019-06-03 02:11:38,"Varberg, Sweden",entrée/plat/dessert,Andre Lugsdin,Sweden,True,False
25,27468,Chip,Halcro,chalcro12@noaa.gov,M,41.0,18.390,126.302057,8.783371,NaN,2019-04-28,False,2019-08-25 21:38:46,"Marihatag, Philippines",entrée/plat/dessert,Chip Halcro,Philippines,NaN,NaN
26,27460,Feliza,Kettlesting,fkettlestingu@51.la,F,63.0,87.840,121.685172,17.535860,NaN,2017-04-10,False,2019-03-31 18:14:55,"Maddarulug Norte, Philippines",entrée/plat/dessert,Feliza Kettlesting,Philippines,NaN,NaN
27,27551,Brigg,Bryett,bbryett3d@prlog.org,M,20.0,28.050,102.638296,24.301245,0746863267,2017-10-25,False,2019-04-10 01:46:26,"Dayingjie, China",entrée/plat/dessert,Brigg Bryett,China,True,True
28,27508,Nicolas,Close,nclose26@topsy.com,M,43.0,86.680,-6.275591,53.350047,NaN,2018-02-12,False,2019-06-08 01:44:19,"Kingscourt, Ireland",entrée/plat/dessert,Nicolas Close,Ireland,NaN,NaN
29,27509,Robinson,Glassopp,rglassopp27@wikimedia.org,M,44.0,86.110,113.778639,26.480043,NaN,2017-11-24,False,2019-09-29 05:43:22,"Xiayang, China",entrée/plat,Robinson Glassopp,China,NaN,NaN
30,27440,Erick,Meharry,emeharrya@wikispaces.com,M,52.0,44.792,3.575175,47.794456,0098166909,2017-04-21,True,2018-07-11 08:22:11,"Auxerre, France",entrée/plat/dessert,Erick Meharry,France,False,False
31,27593,Evelyn,Olenichev,eolenichev4j@tripadvisor.com,F,44.0,54.252,23.711756,37.944288,0214068650,2017-01-02,False,2019-08-07 22:59:39,"Néa Smýrni, Greece",entrée/plat/dessert,Evelyn Olenichev,Greece,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,27564,Lorne,Feak,lfeak3q@icio.us,M,32.0,57.490,8.839032,11.794242,0505884871,2018-01-14,True,2018-07-15 13:11:34,"Wudil, Nigeria",entrée/plat/dessert,Lorne Feak,Nigeria,True,False
176,27444,Selle,Kent,skente@imageshack.us,F,31.0,34.430,-58.567788,-34.612613,07.46.00.85.89,2018-03-15,False,2019-03-17 18:01:41,"Caseros, Argentina",entrée/plat/dessert,Selle Kent,Argentina,True,True
177,27601,Cathrine,Echallie,cechallie4r@nasa.gov,F,32.0,75.020,12.074535,57.732858,NaN,2017-06-09,False,2018-12-10 11:18:19,"Göteborg, Sweden",entrée/plat/dessert,Cathrine Echallie,Sweden,NaN,NaN
178,27437,Rudolf,Steinham,rsteinham7@google.de,M,31.0,99.143,108.801679,-7.627517,06.17.44.23.22,2019-08-24,False,2019-08-24 00:00:00,"Cimrutu, Indonesia",entrée/plat/dessert,Rudolf Steinham,Indonesia,True,True
179,27491,Dilly,Brindle,dbrindle1p@trellian.com,M,23.0,29.490,112.461956,26.974959,NaN,2018-03-24,True,2018-09-15 12:34:09,"Wawu, China",entrée/plat/dessert,Dilly Brindle,China,NaN,NaN
180,27542,Jorey,Dukelow,jdukelow34@aol.com,F,32.0,79.670,122.604584,13.956717,NaN,2019-08-23,False,2019-08-23 00:00:00,"Tagkawayan Sabang, Philippines",entrée/plat/dessert,Jorey Dukelow,Philippines,NaN,NaN
181,27514,Merill,Mulderrig,mmulderrig2c@homestead.com,M,40.0,44.820,45.078261,40.915814,NaN,2017-10-03,False,2019-08-16 01:53:01,"Apaga, Armenia",entrée/plat/dessert,Merill Mulderrig,Armenia,NaN,NaN
183,27609,Orland,Linforth,olinforth4z@hud.gov,M,64.0,55.539,18.326699,52.257205,06.64.22.02.39,2018-09-11,True,2018-09-11 00:00:00,"Konin, Poland",entrée/plat/dessert,Orland Linforth,Poland,True,True
184,27613,Faber,Gerardot,fgerardot53@about.com,M,69.0,37.543,-84.953162,10.270469,NaN,2018-03-17,False,2019-07-06 04:57:32,"Juntas, Costa Rica",entrée/plat/dessert,Faber Gerardot,Costa Rica,NaN,NaN
185,27596,André,Gorz,a.gorz@gmail.com,M,43.0,18.920,88.166695,39.024258,NaN,2019-05-23,False,2019-10-11 20:05:21,"Vosnon, France",entrée/plat/dessert,André Gorz,France,NaN,NaN
187,27470,Conny,Leggatt,cleggatt14@elegantthemes.com,M,31.0,78.331,1.115062,49.400621,NaN,2018-06-05,False,2018-10-30 05:16:18,"Sotteville-lès-Rouen, France",entrée/plat/dessert,Conny Leggatt,France,NaN,NaN
188,27489,Chevalier,Inchley,cinchley1n@technorati.com,M,70.0,70.640,6.034624,49.630638,NaN,2017-09-23,False,2019-03-13 20:03:39,"Mamer, Luxembourg",entrée/plat/dessert,Chevalier Inchley,Luxembourg,NaN,NaN
189,27615,Rosie,Menichino,rmenichino55@newyorker.com,F,26.0,92.460,-48.324286,-10.249091,NaN,2018-04-23,False,2019-03-30 02:30:14,"Palmas, Brazil",entrée/plat/dessert,Rosie Menichino,Brazil,NaN,NaN
190,27492,Laina,Genever,lgenever1q@indiatimes.com,F,51.0,NaN,112.369020,25.587519,NaN,2017-04-24,True,2017-04-24 00:00:00,"Jiahe, China",entrée/plat/dessert,Laina Genever,China,NaN,NaN
191,27488,Merill,Eastop,meastop1m@devhub.com,M,57.0,96.888,106.763895,25.237566,NaN,2017-06-08,False,2019-06-14 21:21:06,"Baliang, China",entrée/plat/dessert,Merill Eastop,China,NaN,NaN
192,27447,Melissa,McIver,mmciverh@drupal.org,F,49.0,47.938,106.230908,38.487193,NaN,2017-06-05,False,2019-09-12 07:49:49,"Yinchuan, China",entrée/plat/dessert,Melissa McIver,China,NaN,NaN
193,27592,Ettore,Featonby,efeatonby4i@hc360.com,M,38.0,19.756,8.271907,50.089714,0466350315,2017-06-12,True,2018-07-14 20:28:17,"Wiesbaden, Germany",entrée/plat/dessert,Ettore Featonby,Germany,True,False
194,27552,Tana,Levine,tlevine3e@netlog.com,F,56.0,94.450,43.100763,44.085486,NaN,2017-08-09,True,2018-06-01 19:39:25,"Vinsady, Russia",entrée/plat/dessert,Tana Levine,Russia,NaN,NaN
195,27557,Zachery,Smewings,zsmewings3j@ucsd.edu,M,31.0,71.852,112.999502,28.190502,NaN,2019-09-08,False,2019-09-08 00:00:00,"Luowan, China",entrée/plat/dessert,Zachery Smewings,China,NaN,NaN
196,27510,Nanny,Irons,nirons28@intel.com,F,53.0,37.345,-68.238534,3.856457,0696703245,2019-04-24,False,2019-04-24 00:00:00,"Inírida, Colombia",entrée/plat/dessert,Nanny Irons,Colombia,True,True
197,27607,Mel,Pelz,mpelz4x@cbslocal.com,M,57.0,24.805,28.678979,7.267512,01.75.20.82.23,2018-10-16,False,2019-07-21 07:58:30,"Tonj, South Sudan",entrée/plat/dessert,Mel Pelz,South Sudan,True,False
198,27624,Dur,Hallaways,dhallaways5e@delicious.com,M,25.0,76.076,106.720976,28.739865,0317009357,2019-07-27,False,2019-09-23 05:01:36,"Ganshui, China",entrée/plat/dessert,Dur Hallaways,China,True,False
199,27604,Michelina,Lowcock,mlowcock4u@nba.com,F,42.0,NaN,12.325710,58.335399,0276520906,2017-07-12,True,2017-07-12 00:00:00,"Vänersborg, Sweden",entrée/plat/dessert,Michelina Lowcock,Sweden,True,False
201,27519,Leonora,Guild,lguild2h@census.gov,F,54.0,60.027,122.195048,7.552335,NaN,2018-12-17,False,2018-12-17 00:00:00,"Siraway, Philippines",entrée/plat/dessert,Leonora Guild,Philippines,NaN,NaN
203,27612,Torrance,Sivills,tsivills52@mapquest.com,M,24.0,36.430,-91.148259,15.027043,NaN,2018-04-03,False,2019-02-08 15:43:59,"Santa Cruz del Quiché, Guatemala",entrée/plat/dessert,Torrance Sivills,Guatemala,NaN,NaN
204,27465,Adelind,Christin,achristinz@blogs.com,F,30.0,90.024,41.427853,52.415968,NaN,2019-06-04,False,2019-06-04 00:00:00,"Znamenka, Russia",entrée/plat/dessert,Adelind Christin,Russia,NaN,NaN
205,27476,Petronella,Pickance,ppickance1a@uiuc.edu,F,28.0,40.865,132.702111,33.762296,NaN,2017-11-22,True,2018-07-29 13:18:29,"Iyo, Japan",entrée/plat/dessert,Petronella Pickance,Japan,NaN,NaN
206,27521,Moritz,Issacof,missacof2j@wired.com,M,21.0,91.970,72.311099,31.263396,0298949280,2018-08-20,False,2019-02-10 16:39:03,"Jhang Sadr, Pakistan",entrée/plat/dessert,Moritz Issacof,Pakistan,True,False
207,27441,Quintana,Foulstone,qfoulstoneb@newsvine.com,F,32.0,61.204,111.138442,-6.783653,0734595126,2018-10-25,False,2018-10-25 00:00:00,"Mantingantengah, Indonesia",entrée/plat/dessert,Quintana Foulstone,Indonesia,True,True
208,27597,Trueman,De Haven,tdehaven4n@goo.gl,M,34.0,81.540,-47.208953,-23.088650,0516973570,2017-06-05,False,2018-10-25 04:20:32,"Indaiatuba, Brazil",entrée/plat/dessert,Trueman De Haven,Brazil,True,False